version: "0.2"
dictionaryDefinitions: []
dictionaries: []
ignoreWords: []
flagWords: []
import: []
ignorePaths:
  - "*.cmake"
  - "*.css"
  - "*.desktop"
  - "*.json"
  - "*.nix"
  - "*.nsi"
  - "*.pri"
  - "*.qrc"
  - "*.rc"
  - "*.rtf"
  - "*.sh"
  - "*.source"
  - "*.svg"
  - "*.ts"
  - "*.ui"
  - "*.xml"
  - "*.yaml"
  - "*.yml"
  - ".ci-scripts/dockerfiles/**"
  - "BUILD.bazel"
  - "Brewfile*"
  - "CHANGELOG.md"
  - "CMakeLists.txt*"
  - "LICENSE*"
  - "_build*/**"
  - "doxygen.conf"
  - "macos/createdmg"
  - "moc_*.cpp"
  - "security/**"
  - "translations/README.md"
  - "windows/cross-compile/check-dlls"
words:
  - "aatest"
  - "abeni"
  - "abilinski"
  - "abtfrm"
  - "acodec"
  - "afrm"
  - "agilob"
  - "alices"
  - "alsoft"
  - "amproperty"
  - "ampropsetid"
  - "anthonybilinski"
  - "appl"
  - "asdfasdf"
  - "asjkdfhawjkeghdfjgh"
  - "avatarbroadcaster"
  - "avcodec"
  - "avcol"
  - "avdevice"
  - "avformat"
  - "avfoundation"
  - "avfrm"
  - "avmedia"
  - "avutil"
  - "bellard"
  - "bilinski"
  - "blabla"
  - "bokm√•l"
  - "borgmann"
  - "chatform"
  - "chatformheader"
  - "chatlist"
  - "codecpar"
  - "codepoint"
  - "codepoints"
  - "coreav"
  - "corefile"
  - "cout"
  - "csizei"
  - "cstdint"
  - "cstring"
  - "cxxflags"
  - "dbootstrap"
  - "dcmake"
  - "demuxer"
  - "dhms"
  - "diadlo"
  - "distros"
  - "dockerfiles"
  - "dspell"
  - "dswitch"
  - "dubslow"
  - "eclevel"
  - "endl"
  - "expfrm"
  - "exuo"
  - "fabrice"
  - "flathub"
  - "frmivalenum"
  - "frmsize"
  - "frmsizeenum"
  - "frnd"
  - "gdigrab"
  - "generalform"
  - "gfrm"
  - "gitter"
  - "gpgsign"
  - "groupchat"
  - "gurmukhi"
  - "haha"
  - "icns"
  - "identicons"
  - "iiibiiay"
  - "integerv"
  - "iphydf"
  - "kriby"
  - "launchable"
  - "ldconfig"
  - "libavcodec"
  - "libavdevice's"
  - "libavformat"
  - "libnotify"
  - "libsodium"
  - "libswscale"
  - "libtoxcore"
  - "listenerf"
  - "localappdata"
  - "locallib"
  - "lojban"
  - "lpolestr"
  - "lrlr"
  - "luca"
  - "makeflags"
  - "malloc"
  - "mallocz"
  - "midlight"
  - "mshxml"
  - "msys"
  - "muxer"
  - "netcam"
  - "noavarice"
  - "nodelist"
  - "nospam"
  - "nurupo"
  - "olestr"
  - "oming"
  - "openal"
  - "opengl"
  - "ostype"
  - "pacman"
  - "pfrm"
  - "pgbtn"
  - "pindir"
  - "pinend"
  - "pire"
  - "pixmap"
  - "pkgbuild"
  - "polla"
  - "profilelocker"
  - "qapp"
  - "qcompare"
  - "qfail"
  - "qgetenv"
  - "qimage"
  - "qlonglong"
  - "qobject"
  - "qputenv"
  - "qreal"
  - "qrencode"
  - "qrwidget"
  - "qsizetype"
  - "qskip"
  - "qssify"
  - "qstyle"
  - "qtbug"
  - "qtest"
  - "qtkit"
  - "qtox"
  - "qtry"
  - "quassel"
  - "qvariant"
  - "qverify"
  - "qwidgetsize"
  - "realpath"
  - "recvq"
  - "regexpsensitive"
  - "relayout"
  - "repasswordline"
  - "repolish"
  - "rofiles"
  - "rtti"
  - "rvalue"
  - "scrn"
  - "sendq"
  - "sinhala"
  - "smileyfied"
  - "smileypack"
  - "smilify"
  - "sourcei"
  - "sqlcipher"
  - "subproject"
  - "svgs"
  - "swresampler"
  - "swscale"
  - "swscaler"
  - "tabber"
  - "tabcompleter"
  - "thilo"
  - "toktok"
  - "toolicons"
  - "toxav"
  - "toxcore"
  - "toxencryptsave"
  - "toxes"
  - "toxext"
  - "toxing"
  - "toxme"
  - "toxq"
  - "toxsave"
  - "uifrm"
  - "uisupport"
  - "ungrab"
  - "unmute"
  - "unmutes"
  - "unpolish"
  - "upgrader"
  - "uyghur"
  - "uyvy"
  - "verifyq"
  - "vfse"
  - "vfve"
  - "vfwcap"
  - "vidioc"
  - "weblate"
  - "wgts"
  - "wzero"
  - "xhost"
  - "yuvj"
  - "yuyv"
  - "zetok"
