name: release

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize]

# Cancel old PR builds when pushing new commits.
concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: TokTok/ci-tools/.github/workflows/release-drafter.yml@master

  release-soon:
    uses: TokTok/ci-tools/.github/workflows/release-soon.yml@master

  netlify:
    uses: TokTok/ci-tools/.github/workflows/netlify.yml@master
    with:
      dockerfile: platform/wasm/Dockerfile
      path: /
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
